### Notification Get

GET {{host}}/Notification


### Notification Create Multi Discord

POST {{host}}/Notification/Multi
Content-Type: application/json

{
	"Datas": [
        {
            "Type": "Discord",
            "Name": "LOL Tracker",
            "IconUrl": "http://2.bp.blogspot.com/-HqSOKIIV59A/U8WP4WFW28I/AAAAAAAAT5U/qTSiV9UgvUY/s1600/icon.png",
            "HookUrl": "",
            "Region": "KR"
	}]
}


### Notification Create Multi Discord (for local debug)

POST {{host}}/Notification/Multi
Content-Type: application/json

{
	"Datas": [
        {
	    "Type": "Discord",
            "Name": "LOL Tracker",
            "IconUrl": "http://2.bp.blogspot.com/-HqSOKIIV59A/U8WP4WFW28I/AAAAAAAAT5U/qTSiV9UgvUY/s1600/icon.png",
            "HookUrl": "",
            "Region": "KR"
	}]
}


### Notification Create

POST {{host}}/Notification
Content-Type: application/json

{
    "Data": {
        "Type": "Discord",
        "Name": "LOL Tracker",
        "IconUrl": "http://2.bp.blogspot.com/-HqSOKIIV59A/U8WP4WFW28I/AAAAAAAAT5U/qTSiV9UgvUY/s1600/icon.png",
        "HookUrl": "",
        "Region": "KR"
    }
}

### Notification Get

GET {{host}}/Notification/5f5a25cc6e6fbaf1a5e7ccca

### Notification Update

PUT {{host}}/Notification/5f5a25cc6e6fbaf1a5e7ccca
Content-Type: application/json

{
    "Data": {
        "Type": "Discord",
        "Name": "LOL Tracker",
        "IconUrl": "http://2.bp.blogspot.com/-HqSOKIIV59A/U8WP4WFW28I/AAAAAAAAT5U/qTSiV9UgvUY/s1600/icon.png",
        "HookUrl": "",
        "Region": "KR"
    }
}

### Notification Delete

DELETE {{host}}/Notification/5f5a25cc6e6fbaf1a5e7ccca

