### Tracking Create

POST {{host}}/Tracking
Content-Type: application/json

{
    "SummonerName":"스펠 미아",
    "Region": "KR",
    "Switch": true
}

### Tracking Get

GET {{host}}/Tracking?summonerName=elky&region=KR

### Tracking Update

PUT {{host}}/Tracking/elky
Content-Type: application/json

{
    "Region": "KR",
    "Switch": true
}

### Tracking Delete

DELETE {{host}}/Tracking/elky
Content-Type: application/json

{
    "Region": "KR"
}
